# Make sure using latest Homebrew
update || true

# Update already-installed formula
upgrade || true

# Add Repository
tap homebrew/versions    || true
tap phinze/homebrew-cask || true
tap homebrew/binary      || true
tap thoughtbot/formulae  || true

# Packages

## Shell
install zsh   || true

## Git
install git   || true
install hub   || true
install tig   || true

## Utils
install autoconf  || true
install automake  || true
install rmtrash   || true
install coreutils || true
install rmtrash   || true
install wget      || true
install curl      || true
install proctools || true
install tree      || true
install openssl   || true
install libyaml   || true
install readline  || true
install tmux      || true
install markdown  || true
install nkf       || true
install ag        || true
install fasd      || true
install reattach-to-user-namespace || true


## Languages
install chruby           || true
install ruby-install     || true

## DevOps
install docker      || true
install boot2docker || true
install packer      || true

## Image
install imagemagick || true

# Casks
install brew-cask
cask install google-chrome || true
cask install iterm2        || true
cask install dropbox       || true
cask install alfred        || true
cask install sublime-text  || true
cask install virtualbox    || true
cask install vagrant       || true
cask install dash          || true
cask install flux          || true
cask install onepassword   || true
cask install p4merge       || true
cask install seil          || true
cask install spectacle     || true

# Remove outdated versions
cleanup
