cask_args appdir: '/Applications'

# Add Repository
tap 'thoughtbot/formulae'
tap 'homebrew/cask-fonts'

# Packages

## Shell
brew 'fish'

## Git
brew 'git'
brew 'tig'

## Utils
brew 'wget'
brew 'curl'
brew 'tree'
brew 'openssl'
brew 'libyaml'
brew 'fzf'
brew 'fd'
brew 'grc'
brew 'bat'
brew 'neovim'
brew 'coreutils'
brew 'asdf'
brew 'exa'
brew 'ag'

## Languages
# brew 'chruby'
# brew 'ruby-install'

# Casks
cask 'google-chrome'
cask 'iterm2'
cask 'clipy'
cask 'rectangle'
cask 'font-hack-nerd-font'
cask 'postico'
cask 'font-fira-code'
cask 'sublime-text'
