Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, path: "~/.dotfiles/home/vagrant/bootstrap.sh"

  config.vm.network "private_network", ip: "10.0.3.15"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 9292, host: 9292
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9100, host: 9100
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 8080, host: 8080 
  config.vm.network "forwarded_port", guest: 80, host: 80 
  config.ssh.forward_agent = true

  config.vm.synced_folder ".", "/home/vagrant/shared",
    type:          "nfs",
    create:        true,
    mount_options: ["vers=3", "udp", "nolock"]

  config.vm.provider "virtualbox" do |vm|
    vm.memory = 8192
    vm.cpus = 4
    vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
end
